<?php

namespace spec\Practice;

use Practice\Valley;
use PhpSpec\ObjectBehavior;
use Prophecy\Argument;

class ValleySpec extends ObjectBehavior
{
    function it_is_return_zero_if_input_eight()
    {
        $this->countingValleys(8, 'UDUDUDUD')->shouldReturn(0);
    }

    function it_is_return_one_if_input_eight()
    {
        $this->countingValleys(8, 'DDUUUUDD')->shouldReturn(1);
    }

    function it_is_return_zero_if_input_ten()
    {
        $this->countingValleys(10, 'UDUUUDUDDD')->shouldReturn(0);
    }

    function it_is_return_one_if_input_ten()
    {
        $this->countingValleys(10, 'UDDDUDUDUU')->shouldReturn(1);
    }

    function it_is_return_two_if_input_twelve()
    {
        $this->countingValleys(12, 'DDUUDDUDUUUD')->shouldReturn(2);
    }

    function it_is_return_one_if_input_thousand()
    {
        $this->countingValleys(1000, 'DDDUUUUUDDDUUDUDDDUUDUUDDDUUDDDDDUDDUUDUDDUDUDDUDDDUDUUDUDUDDUDDDDDDDUUUUUUUUDUUDUUUUDUDDDUDDUUDUDDUDUDUUUUUUDUDDDDDDUDDDUUUDDUDDUDDUUUUDDDDUDUUUUUDUUDUDDUUUDUUUDDUDDDDUUUUDDDDDDUUUUDDDDUDDUUDDDDUUDUDDUUDUUUDUUUUDDUDDDDUUDUDDDDDUDUDUDUUDDUDUDDUDDDDUDUDUDUUUDDDDDUUUDDDUDDDUDDDDUDUDUDDUDDDDDDUDUDUDDDDDDUUUDDDUDUUDDDDUDUDDDDDUDDUUDUDDDDUDDDUUUUUDUDDUDUUDUDDDDUUUUDDDUDUUUUUUUDUUDDDUDUDDDDUDDUUDDDDDUDDUUUUDUUDUDDUDUUDDUUUDUUUUDDUUUUDDUUDUUUDUDUUUDUDDUDDDUDUUUUUUUUUUUDUDDUDDDDDUUDUDDUDDUDUDUUDDDDUUUDDUDDUDDUUDUUUDUDUUUUUDDUUDUUDUDDUDUUUUUUDDDDUUUDDUDUUUUUUUDDUUDDUUUUUDDUUDUUUDDUDUDUUDDDUDUUUUUUUDUUUUDDUDDDUDUUDUDDDUDUUUDUUUDDDUDDUUUUUDUUDDDDDDUUDDUDUDDUDUDUDDUDUDUUUDUDUUDUDUUDUDUDDDDUUUUDDDUUDUUDDUDUDUUDUDUUUDDUUUDUDUDDDUDDUUUDUDUUUDDUDUDUDDUUDDDDUUUUUDUDUUDUDUUDDDDUDDDUDUUUUUDDDUDDDDUUDDUUDUUUUUUDDUUDDUUUUUUUDUDDUDDDDDDDUDDDDUDUDUDUUDUDDDUDUUUUDDUUUDUDUDUUDDDDDUUUUUUDUDDUDUDDUDDUDUUDUDUUUUUDUDDDDUUUDDUUDDDUUUUDUDDDUDDUUUDDDDUDDDUDDDUUDDDDUUDDDUDDDUUUUUUDUDUUDUUDUDDDUDUUDDUDDDDUDUDUUUUUUUUUU')->shouldReturn(18);
    }
}
